import { User, Patient, BpReading, WorkflowTask, CommunicationLog } from '../types'

export const mockUsers: User[] = [
  {
    id: 1,
    username: 'admin',
    name: 'System Administrator',
    role: 'admin',
    email: 'admin@firestation.gov',
    phone: '555-0101',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 2,
    username: 'nurse_sarah',
    name: 'Sarah Johnson',
    role: 'nurse',
    email: 'sarah.johnson@firestation.gov',
    phone: '555-0102',
    createdAt: new Date('2024-01-02'),
  },
  {
    id: 3,
    username: 'coach_mike',
    name: 'Mike Williams',
    role: 'coach',
    email: 'mike.williams@firestation.gov',
    phone: '555-0103',
    createdAt: new Date('2024-01-03'),
  },
]

export const mockPatients: Patient[] = [
  {
    id: 1,
    employeeId: 'FF001',
    firstName: 'John',
    lastName: 'Smith',
    department: 'Station 1',
    union: 'IAFF Local 123',
    age: 35,
    email: 'john.smith@firestation.gov',
    phone: '555-1001',
    emergencyContact: '555-1002',
    medications: 'Lisinopril 10mg',
    allergies: 'None',
    lastCheckup: new Date('2024-06-01'),
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 2,
    employeeId: 'FF002',
    firstName: 'Maria',
    lastName: 'Garcia',
    department: 'Station 2',
    union: 'IAFF Local 123',
    age: 42,
    email: 'maria.garcia@firestation.gov',
    phone: '555-1003',
    emergencyContact: '555-1004',
    medications: 'Metoprolol 25mg',
    allergies: 'Penicillin',
    lastCheckup: new Date('2024-05-15'),
    customSystolicThreshold: 130,
    customDiastolicThreshold: 85,
    createdAt: new Date('2024-01-16'),
  },
  {
    id: 3,
    employeeId: 'FF003',
    firstName: 'Robert',
    lastName: 'Johnson',
    department: 'Station 1',
    union: 'IAFF Local 123',
    age: 28,
    email: 'robert.johnson@firestation.gov',
    phone: '555-1005',
    emergencyContact: '555-1006',
    medications: 'None',
    allergies: 'Shellfish',
    lastCheckup: new Date('2024-06-10'),
    createdAt: new Date('2024-01-17'),
  },
]

export const mockBpReadings: BpReading[] = [
  {
    id: 1,
    patientId: 1,
    systolic: 145,
    diastolic: 92,
    heartRate: 78,
    notes: 'Post-exercise reading',
    recordedBy: 2,
    recordedAt: new Date('2024-06-15T10:30:00'),
    isAbnormal: true,
    category: 'stage1',
  },
  {
    id: 2,
    patientId: 2,
    systolic: 165,
    diastolic: 98,
    heartRate: 82,
    notes: 'Patient reported stress',
    recordedBy: 2,
    recordedAt: new Date('2024-06-14T14:15:00'),
    isAbnormal: true,
    category: 'stage2',
  },
  {
    id: 3,
    patientId: 3,
    systolic: 118,
    diastolic: 76,
    heartRate: 72,
    notes: 'Normal routine check',
    recordedBy: 2,
    recordedAt: new Date('2024-06-13T09:45:00'),
    isAbnormal: false,
    category: 'normal',
  },
  {
    id: 4,
    patientId: 1,
    systolic: 135,
    diastolic: 88,
    heartRate: 75,
    notes: 'Follow-up reading',
    recordedBy: 2,
    recordedAt: new Date('2024-06-12T11:20:00'),
    isAbnormal: true,
    category: 'stage1',
  },
]

export const mockWorkflowTasks: WorkflowTask[] = [
  {
    id: 1,
    patientId: 1,
    assignedTo: 2,
    title: 'Follow-up on Stage 1 Hypertension - John Smith',
    description: 'Patient has consistent Stage 1 readings. Schedule follow-up appointment and discuss lifestyle modifications.',
    priority: 'high',
    status: 'pending',
    dueDate: new Date('2024-06-20'),
    createdAt: new Date('2024-06-15'),
  },
  {
    id: 2,
    patientId: 2,
    assignedTo: 3,
    title: 'Urgent: Stage 2 Hypertension - Maria Garcia',
    description: 'Patient shows Stage 2 hypertension. Immediate intervention required. Contact patient within 24 hours.',
    priority: 'urgent',
    status: 'in_progress',
    dueDate: new Date('2024-06-16'),
    createdAt: new Date('2024-06-14'),
  },
]

export const mockCommunicationLogs: CommunicationLog[] = [
  {
    id: 1,
    patientId: 1,
    userId: 2,
    type: 'call',
    message: 'Called patient regarding elevated BP reading. Discussed dietary changes and exercise routine.',
    notes: 'Patient receptive to recommendations. Scheduled follow-up in 2 weeks.',
    outcome: 'resolved',
    followUpDate: new Date('2024-06-29'),
    createdAt: new Date('2024-06-15T16:30:00'),
  },
  {
    id: 2,
    patientId: 2,
    userId: 3,
    type: 'call',
    message: 'Attempted to contact patient about Stage 2 hypertension reading.',
    notes: 'No answer. Left voicemail requesting callback.',
    outcome: 'no_answer',
    followUpDate: new Date('2024-06-16'),
    createdAt: new Date('2024-06-14T17:45:00'),
  },
]